name: Laboratorio Pia
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49535804986953735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3d3d3'
    - '#6f6f6f'
    - '#393939'
    - '#020202'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
